//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SmartRenameUI.rc
//
#define ID_RENAME 8
#define ID_ABOUT 9
#define IDD_SMARTRENAME_DIALOG 102
#define IDS_APP_TITLE 103
#define IDM_ABOUT 104
#define IDS_RENAMED 104
#define IDS_ORIGINAL 105
#define IDS_LISTVIEW_EMPTY 106
#define IDS_ENTIREITEMNAME 107
#define IDS_NAMEONLY 108
#define IDS_EXTENSIONONLY 109
#define IDC_SMARTRENAME 110
#define IDS_COUNTSLABELFMT 111
#define IDS_LOADING 112
#define IDS_LOADING_MSG 113
#define IDR_MAINFRAME 128
#define IDD_MAIN 129
#define IDI_RENAME 132
#define IDC_EDIT_SEARCHFOR 1002
#define IDC_EDIT_REPLACEWITH 1003
#define IDC_LIST_PREVIEW 1004
#define IDC_CHECK_USEREGEX 1005
#define IDC_STATUS_MESSAGE 1006
#define IDC_CHECK_EXCLUDESUBFOLDERS 1007
#define IDC_CHECK_ENUMITEMS 1008
#define IDC_CHECK_EXCLUDEFILES 1009
#define IDC_CHECK_CASESENSITIVE 1010
#define IDC_CHECK_MATCHALLOCCURRENCES 1011
#define IDC_CHECK_EXCLUDEFOLDERS 1012
#define IDC_CHECK_NAMEONLY 1013
#define IDC_CHECK_EXTENSIONONLY 1014
#define IDC_PREVIEWGROUP 1015
#define IDC_OPTIONSGROUP 1016
#define IDC_SEARCHREPLACEGROUP 1017
#define IDC_STATIC -1

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC 1
#define _APS_NEXT_RESOURCE_VALUE 133
#define _APS_NEXT_COMMAND_VALUE 32771
#define _APS_NEXT_CONTROL_VALUE 1018
#define _APS_NEXT_SYMED_VALUE 110
#endif
#endif
